# This is a basic workflow to help you get started with Actions

name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Run Danger
      run: |
        gem install bundler
        
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        
        bundle exec danger --verbose
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUNNING_IN_ACTIONS: true
