# This is a basic workflow to help you get started with Actions

name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Danger
      uses: danger/danger@8.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
