# This is a basic workflow to help you get started with Actions

name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/swift@3.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
