name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Swiftlint
        run: |
          curl -LJO https://github.com/realm/SwiftLint/releases/download/0.40.3/swiftlint_linux.zip
          unzip swiftlint_linux.zip
          ./swiftlint --config .swiftlint.yml --reporter github-actions-logging
